apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shopverse-db-secret
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: shopverse-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: shopverse/db-credentials
        property: password
    - secretKey: DB_ROOT_PASSWORD
      remoteRef:
        key: shopverse/db-credentials
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: shopverse/jwt-secret
        property: secret
